<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>QSearch</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>QSearch</ApplicationTitle>


		<!-- App Identifier -->
		<ApplicationId>com.mohdzed.qsearch</ApplicationId>
		<ApplicationIdGuid>739d3cd0-12fe-4bd6-8400-216055e3842d</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>6.4.2</ApplicationDisplayVersion>
		<ApplicationVersion>16.1.0</ApplicationVersion>
		<!-- Android Only-->
		<AndroidVersionCode>41</AndroidVersionCode>
		<UseMaterial3>true</UseMaterial3>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>-->
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
	  <DebugType>portable</DebugType>
	  <Optimize>false</Optimize>
	  <WarningLevel>4</WarningLevel>
	  <RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm64;android-arm;android-x64;android-x86</RuntimeIdentifiers>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	  <CodesignProvision>Automatic</CodesignProvision>
	  <CodesignEntitlements>Platforms\iOS\Entitlements.plist</CodesignEntitlements>
	  <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
	   <MtouchOptimizePNGs>true</MtouchOptimizePNGs>
	   <MtouchInterpreter>all</MtouchInterpreter>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-maccatalyst|AnyCPU'">
	  	<MtouchLink>SdkOnly</MtouchLink>
		<EnableCodeSigning>True</EnableCodeSigning>
  		<EnablePackageSigning>true</EnablePackageSigning>
  		<CreatePackage>true</CreatePackage>
	  	<CodesignKey>Mac OS Distribution: Muhammad Zahid (NTMXQ4647V)</CodesignKey>
	  	<CodesignProvision>Mac OS Distribution</CodesignProvision>
	  	<EnablePackageSigning>true</EnablePackageSigning>
		<PackageSigningKey>3rd Party Mac Developer Installer: Muhammad Zahid (NTMXQ4647V)</PackageSigningKey>
		<CodesignEntitlements>Platforms\MacCatalyst\Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
		<EnableCodeSigning>true</EnableCodeSigning>
		<CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
		<DisableCodesignVerification>true</DisableCodesignVerification>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <AndroidSigningKeyStore>/Users/MZee/Library/Developer/Xamarin/Keystore/MyQSearch/MyQSearch.keystore</AndroidSigningKeyStore>
	  <AndroidSigningKeyAlias>myqsearch</AndroidSigningKeyAlias>
	  <AndroidEnableSGenConcurrent>false</AndroidEnableSGenConcurrent>
	  <RunAOTCompilation>true</RunAOTCompilation> 
	  <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
	  <PublishTrimmed>true</PublishTrimmed>
	  <StripDebugSymbols>true</StripDebugSymbols>
	  <Optimize>true</Optimize>
	  <AndroidLinkMode>SdkOnly</AndroidLinkMode> 
	  <AndroidLinkTool>r8</AndroidLinkTool>
	  <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	  <RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm64;android-arm;android-x64;android-x86</RuntimeIdentifiers>
	</PropertyGroup>
	<!-- <PropertyGroup Condition="'$(TargetFramework)'=='net8.0-maccatalyst'">
	<ApplicationTitle>Your App Name</ApplicationTitle>
	<RuntimeIdentifier>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifier>
	</PropertyGroup> -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModelSavedState" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common.Java8" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Process" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.ViewModel.Ktx" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime.Ktx" Version="2.9.4" />
	  <PackageReference Include="Xamarin.AndroidX.SavedState.SavedState.Ktx" Version="1.3.3" />
	</ItemGroup>
	<ItemGroup>
	  <MauiImage Remove="Resources\Images\tick_mark.svg" />
	</ItemGroup>
	<ItemGroup>
		<!-- App Icon -->
		<MauiImage Include="Resources\Images\*" />
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />
		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Sentry.Maui" Version="5.16.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.10" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />

	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Splash\" />
	  <None Remove="Resources\Splash\quransplash-1.png" />
	  <None Remove="Resources\Splash\quransplash-1.svg" />
	  <None Remove="Resources\Splash\quransplash1.svg" />
	  <None Remove="Resources\Fonts\Tahoma.ttf" />
	  <None Remove="Models\" />
	  <None Remove="Platforms\Android\Resources\drawable\" />
	  <None Remove="Resources\Fonts\MaterialIcons-Regular.ttf" />
	  <None Remove="Resources\Fonts\MaterialIconsOutlined-Regular.otf" />
	  <None Remove="Resources\Images\about.svg" />
	  <None Remove="Resources\Raw\quran.sqlite" />
	  <None Remove="Resources\Splash\quransearch-2.svg" />
	  <None Remove="Resources\Splash\qsearchsplash-2.svg" />
	  <None Remove="Resources\Splash\qssplash.svg" />
	  <None Remove="Resources\AppIcon\" />
	  <None Remove="Resources\AppIcon\appicon.svg" />
	  <None Remove="Resources\AppIcon\appiconfg.svg" />
	  <None Remove="Resources\Fonts\NotoNaskhArabic-Regular.ttf" />
	  <None Remove="Resources\Images\qsearch-bkg.svg" />
	  <None Remove="Resources\Images\qsearch-header.svg" />
	  <None Remove="Resources\Images\tick_mark.svg" />
	  <None Remove="Resources\Images\tick_mark1.svg" />
	  <None Remove="Resources\Images\tick_mark1.png" />
	  <None Remove="Resources\Fonts\AlQuran-IndoPak-by-QuranWBW.v.4.2.2-WL.ttf" />
	  <None Remove="Resources\Fonts\Lateef-Bold.ttf" />
	  <None Remove="Resources\Fonts\AlQalam.ttf" />
	  <None Remove="Resources\Images\qsearch_hdr4.svg" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Resources\Splash\" />
	  <Folder Include="Models\" />
	  <Folder Include="Platforms\Android\Resources\drawable\" />
	  <Folder Include="Resources\AppIcon\" />
	</ItemGroup>
	<ItemGroup>
	  <BundleResource Include="Resources\Fonts\Tahoma.ttf" />
	  <BundleResource Include="Resources\Fonts\MaterialIcons-Regular.ttf" />
	  <BundleResource Include="Resources\Fonts\MaterialIconsOutlined-Regular.otf" />
	  <BundleResource Include="Resources\AppIcon\appicon.svg" />
	  <BundleResource Include="Resources\Fonts\NotoNaskhArabic-Regular.ttf" />
	  <BundleResource Include="Resources\Images\tick_mark1.svg" />
	  <BundleResource Include="Resources\Fonts\IndoPak.ttf" />
	  <BundleResource Include="Resources\Fonts\Lateef-Bold.ttf" />
	  <BundleResource Include="Resources\Fonts\AlQalam.ttf" />
	  <BundleResource Include="Resources\Fonts\NotoNastaliqUrdu-VariableFont_wght.ttf" />
	</ItemGroup>
	<ItemGroup>
	  <MauiFont Remove="Resources\Fonts\AlQuran-IndoPak-by-QuranWBW.v.4.2.2-WL.ttf" />
	</ItemGroup>
	<ItemGroup>
	  <MauiSplashScreen Include="Resources\Splash\qssplash.svg" color="#799116" />
	</ItemGroup>
	<ItemGroup>
	  <MauiIcon Include="Resources\AppIcon\appiconfg.svg" />
	</ItemGroup>
	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />
	</ItemGroup>
	<ItemGroup>
	  <MauiCss Remove="Resources\Raw\qs.css" />
	</ItemGroup>
	<ItemGroup>
	  <MauiAsset Remove="Resources\Raw\qs.css" />
	</ItemGroup>

</Project>
